var captureControlApp = angular.module('captureControlApp', ['ngRoute', 'ngCookies', 'ngSanitize', 'ui.grid']);

captureControlApp.config(function($routeProvider, $locationProvider){
	$locationProvider.hashPrefix('');
	$routeProvider
		.when("/", { 
			templateUrl: "/include/dashboard/dashboard.html"   
		}).when("/products", { 
			templateUrl: "/include/product/products.html"   
		}).when("/products/:id", { 
			templateUrl: "/include/product/product-details.html"   
		}).when("/products/skus/:id", { 
			templateUrl: "/include/product/sku-details.html"   
		}).when("/products/skus/inventory/:id", { 
			templateUrl: "/include/product/inventory-details.html"   
		}).when("/prd-dashboard", { 
			templateUrl: "/include/product/dashboard.html"   
		}).when("/products/skus/bundles/:id", { 
			templateUrl: "/include/product/sku-bundle-details.html"   
		}).when("/purchase", { 
			templateUrl: "/include/purchase/pos.html"   
		}).when("/purchase/:id", { 
			templateUrl: "/include/purchase/po-details.html"   
		}).when("/purchase/state/:state", { 
			templateUrl: "/include/purchase/po-listing-by-type.html"   
		}).when("/new-purchase-order", { 
			templateUrl: "/include/purchase/new-po.html"   
		}).when("/purchase-reorder/:id", { 
			templateUrl: "/include/purchase/re-order.html"   
		}).when("/po-dashboard", { 
			templateUrl: "/include/purchase/dashboard.html"   
		}).when("/vendor-price-lists", { 
			templateUrl: "/include/purchase/pricelists.html"   
		}).when("/vendor-price-list/:id", { 
			templateUrl: "/include/purchase/pricelist-details.html"   
		}).when("/app/purchase/settings", { 
			templateUrl: "/include/purchase/purchase-config.html"   
		}).when("/invoice", { 
			templateUrl: "/include/invoice/invoices.html"   
		}).when("/invoice/:id", { 
			templateUrl: "/include/invoice/invoice-details.html"   
		}).when("/order", { 
			templateUrl: "/include/order/orders.html"   
		}).when("/so-dashboard", { 
			templateUrl: "/include/order/dashboard.html"   
		}).when("/order/:id", { 
			templateUrl: "/include/order/order-details.html"   
		}).when("/new-order", { 
			templateUrl: "/include/order/new-order.html"   
		}).when("/crm", { 
			templateUrl: "/include/crm/organizations.html"   
		}).when("/crm/:id", { 
			templateUrl: "/include/crm/organization-details.html"   
		}).when("/access-management/users", { 
			templateUrl: "/include/crm/users.html"   
		}).when("/access-management/user/:id", { 
			templateUrl: "/include/crm/user-details.html"   
		}).when("/access-management/myaccount", { 
			templateUrl: "/include/crm/my-account.html"   
		}).when("/packing", { 
			templateUrl: "/include/warehouse/packing.html"   
		}).when("/wms-dashboard", { 
			templateUrl: "/include/warehouse/dashboard.html"   
		}).when("/packing", { 
			templateUrl: "/include/warehouse/packing.html"   
		}).when("/pack-details/:id", { 
			templateUrl: "/include/warehouse/pack-details.html"   
		}).when("/picking", { 
			templateUrl: "/include/warehouse/picking.html"   
		}).when("/pick-details/:id", { 
			templateUrl: "/include/warehouse/pick-details.html"   
		}).when("/shipping", { 
			templateUrl: "/include/warehouse/shipping.html"    
		}).when("/ship-details/:id", { 
			templateUrl: "/include/warehouse/ship-details.html"    
		}).when("/app/warehouse/settings", { 
			templateUrl: "/include/warehouse/warehouse-config.html"   
		}).when("/admin/settings", { 
			templateUrl: "/include/admin/config.html"   
		}).when("/admin/app-config", { 
			templateUrl: "/include/admin/app-config.html"   
		}).when("/app/products/settings", { 
			templateUrl: "/include/product/product-config.html"   
		}).when("/app/order/settings", { 
			templateUrl: "/include/order/order-config.html"   
		}).when("/app/edgehubs/settings", { 
			templateUrl: "/include/edgehubs/edgehub-config.html"   
		}).when("/edgehubs", { 
			templateUrl: "/include/edgehubs/edgehubs.html" 
		}).when("/edgehubs/:id", { 
			templateUrl: "/include/edgehubs/edgehub.html"   
		}).when("/edgehubs/tags", { 
			templateUrl: "/include/edgehubs/tags.html"   
		}).when("/import", { 
			templateUrl: "/include/import/inventory-import.html"   
		}).when("/admin/app-integration", { 
			templateUrl: "/include/integration/integrations.html"   
		}).when("/admin/app-search", { 
			templateUrl: "/include/admin/app-search.html"   
		}).when("/transfer", { 
			templateUrl: "/include/warehouse/transfer-list.html"   
		}).when("/transfer/:id", { 
			templateUrl: "/include/warehouse/transfer.html"   
		}).when("/serviceorder", { 
			templateUrl: "/include/service/service-orders.html"   
		}).when("/serviceorder/:id", { 
			templateUrl: "/include/service/service-order-details.html"   
		}).when("/new-serviceorder", { 
			templateUrl: "/include/service/new-service-order.html"   
		}).when("/rma", { 
			templateUrl: "/include/rma/rmas.html"   
		}).when("/rma/:id", { 
			templateUrl: "/include/rma/rma-details.html"   
		}).when("/reporting", { 
			templateUrl: "/include/reporting/landing.html"   
		}).when("/reporting/inventory-count-location", { 
			templateUrl: "/include/reporting/reports/inventory/inventory-count-location.html"   
		}).when("/reporting/product-availability", { 
			templateUrl: "/include/reporting/reports/inventory/product-availability.html"   
		}).when("/reporting/inventory-availability", { 
			templateUrl: "/include/reporting/reports/inventory/inventory-availability.html"   
		}).when("/reporting/sales-orders-by-dates", { 
			templateUrl: "/include/reporting/reports/sales/sales-orders-by-date.html"   
		}).when("/reporting/inventory-adjustments", { 
			templateUrl: "/include/reporting/reports/inventory/inventory-adjustments.html"   
		}).when("/reporting/inventory-receipts", { 
			templateUrl: "/include/reporting/reports/inventory/inventory-receipts.html"   
		}).when("/reporting/inventory-spot-count", { 
			templateUrl: "/include/reporting/reports/inventory/inventory-spot-count.html"   
		}).when("/reporting/inventory-audit", { 
			templateUrl: "/include/reporting/reports/inventory/inventory-audit-listing.html"   
		}).when("/reporting/inventory-audit-new", { 
			templateUrl: "/include/reporting/reports/inventory/inventory-new-audit.html"   
		}).when("/reporting/inventory-audit/:id", { 
			templateUrl: "/include/reporting/reports/inventory/inventory-audit-details.html"   
		}).when("/reporting/inventory-transfers", { 
			templateUrl: "/include/reporting/reports/inventory/inventory-transfers.html"   
		}).when("/reporting/cancelled-sales-orders", { 
			templateUrl: "/include/reporting/reports/sales/cancelled-sales-orders-by-date.html"   
		}).when("/reporting/backordered-sales-orders", { 
			templateUrl: "/include/reporting/reports/sales/backordered-sales-orders.html"   
		}).when("/reporting/overdue-sales-orders", { 
			templateUrl: "/include/reporting/reports/sales/overdue-sales-orders.html"   
		}).when("/reporting/sales-orders-by-salesperson", { 
			templateUrl: "/include/reporting/reports/sales/sales-orders-by-sales-person.html"   
		}).when("/reporting/sales-orders-by-customer", { 
			templateUrl: "/include/reporting/reports/sales/sales-orders-by-customer.html"   
		});
});